version: '3.9'

services:
  frontend:
    build: ./web
    restart: always
    # network_mode: host
    init: true
    env_file:
      - ./web/.env.development

  api:
    build: ./server
    restart: always
    # network_mode: host
    init: true
    # depends_on:
    #   - db
    env_file:
      - ./server/.env

  db:
    image: postgres:13.3-alpine
    restart: always
    # network_mode: host
    init: true
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
