FROM node:16-alpine as builder

WORKDIR /home/node
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build --production


FROM node:16-alpine
ENV NODE_ENV=production
ENV ENV_SILENT=true
ENV HOST=0.0.0.0
ENV PORT=3333
ENV APP_KEY=
WORKDIR /home/node
COPY --from=builder /home/node/build .
RUN npm ci --production
EXPOSE 3333

CMD [ "node", "server.js" ]
